name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Lint (ruff)
        run: uv run ruff check .
      - name: Format check (black)
        run: uv run black --check .
      - name: Tests (quick)
        run: uv run pytest -m "not slow" -q
